PUT http://localhost:8080/events/1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBldGVyMUBmaXJzdC5jb20iLCJleHAiOjE3MTE0NzU5MTMsInVzZXJJZCI6MX0.dCLMl7lZvqUhcQqCPNa-40QWtw8TNxFFH9jtnjrvVhw

{
  "name": "Event1 updated",
  "description": "Peters event!!!",
  "location": "Test location changed",
  "dateTime": "2025-04-20T15:45:00.000Z"
}